### ISSUE TITLE
Outdated pillow dependency

### ISSUE THREAD

**Issue by thomaswitt** [Paularossi/AdDownloader#4]
@Paularossi  There's a dependency to pillow 10.2.0 which is outdated and doesn't work anymore with current python environments. In order to make it work again, pls updated to pillow 11.0.0

```
Collecting pillow==10.2.0 (from AdDownloader==0.2.10)
  Using cached pillow-10.2.0.tar.gz (46.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "/Users/thomas/Dev/misc/meta/AdDownloader/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/Users/thomas/Dev/misc/meta/AdDownloader/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/thomas/Dev/misc/meta/AdDownloader/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/yn/x06vl6hn3n3gn4m171nwvp2h0000gn/T/pip-build-env-0u6m69aa/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/yn/x06vl6hn3n3gn4m171nwvp2h0000gn/T/pip-build-env-0u6m69aa/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/private/var/folders/yn/x06vl6hn3n3gn4m171nwvp2h0000gn/T/pip-build-env-0u6m69aa/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 31, in <module>
        File "<string>", line 28, in get_version
      KeyError: '__version__'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by Paularossi** [comment]
Hi @thomaswitt,

Thanks for highlighting this issue. I have updated AdDownloader to use pillow 11.0.0 and released a new version: [v0.2.11](https://github.com/Paularossi/AdDownloader/releases/tag/v0.2.11)

**Comment by thomaswitt** [comment]
Hey @Paularossi, I did on MacOS

```bash
❯ cd /Users/thomas/Dev/misc/socialmedia
❯ git clone https://github.com/Paularossi/AdDownloader.git
Cloning into 'AdDownloader'...
remote: Enumerating objects: 904, done.
remote: Counting objects: 100% (306/306), done.
remote: Compressing objects: 100% (229/229), done.
remote: Total 904 (delta 217), reused 156 (delta 76), pack-reused 598 (from 1)
Receiving objects: 100% (904/904), 67.92 MiB | 31.97 MiB/s, done.
Resolving deltas: 100% (571/571), done.
❯ cd AdDownloader
❯ python3 -m venv myenv
❯ source myenv/bin/activate
❯ python -m AdDownloader.cli
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/thomas/Dev/misc/socialmedia/AdDownloader/AdDownloader/cli.py", line 9, in <module>
    import typer
ModuleNotFoundError: No module named 'typer'
```

Then I had to add several modules via `pip3 install` (via trial and error)
```
❯ pip3 install typer
❯ pip3 install inquirer3
❯ pip3 install pandas
❯ pip3 install requests
❯ pip3 install pillow
❯ pip3 install selenium
❯ pip3 install opencv-python
```

so I could finally run `python -m AdDownloader.cli`.

Got it now halfway working, but I got

```
Ad data download will begin now.
##### Starting reading page 1 #####
##### Starting reading page 2 #####
##### Starting reading page 3 #####
##### Starting reading page 4 #####
##### Starting reading page 5 #####
##### Starting reading page 6 #####
##### Starting reading page 7 #####
##### Starting reading page 8 #####
##### Starting reading page 9 #####
##### Starting reading page 10 #####
Page 10 is empty.
Done downloading 9 json files for the given parameters.
Data processing will start now.
No data was downloaded. Please try a new request.
Download finished in 0 minutes and 41 seconds.
```

Any idea?

**Comment by Paularossi** [comment]
Hi @thomaswitt , sorry for the trouble. The underlying issue was that cloning the repo and running python -m AdDownloader.cli directly skips the install step entirely, so none of the dependencies (including pillow) actually get installed that way. 
python -m pip install . from the repo root is required first (I added this in the README now).

While fixing this I also found and fixed a few more cross-platform install issues your report surfaced indirectly: torch was pinned to a version with no wheel for Intel Mac, requires-python had no upper bound so newer Pythons (3.12+) would hit dependency versions with no published wheels at all, and an unnecessary datetime dependency (known to cause pandas import conflicts) has been removed. All of this is in v0.3.0, just released. 

I will close this issue, but please reopen if you still hit install issues on the new version!
